version: '3'
services:
  build_tools:
    container_name: build_tools
    build: .
    volumes:
      - .:/root/build_tools
      - ../android:/root/build_tools/android
      - ../../env:/root/build_tools/env